app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/GetStartedSwift
  command: bash -c "cd /GetStartedSwift && swift package clean && swift build && swift test && ./.build/debug/kitura-helloworld"
